// Generated by https://quicktype.io

export interface CategoryResponse {
  data: DataCategory;
}

export interface DataCategory {
  getCategories: GetCategory[];
}

export interface GetCategory {
  id: string;
  name: string;
}

export interface AddResponse {
  data?: DataAddProduct;
}

export interface DataAddProduct {
  addProduct: string;
}

// Generated by https://quicktype.io

export interface ProductResponse {
  getProducts: GetProduct[];
}

export interface GetProduct {
  id: string;
  name: string;
  price: number;
  category: string;
  description: string;
  available: boolean;
  img: null | string;
}
